version: "3.9"
services:
  benchmark:
    build: .
    command: ./run_profile.sh
    volumes:
      - ./:/code
    stdin_open: true
    tty: true
    entrypoint: /bin/bash
  interactive:
    image: filestats_benchmark
    volumes:
      - ./:/code
    stdin_open: true
    tty: true
    entrypoint: /bin/bash